"""Add cascade deletion

Revision ID: 0191f5acdfa7
Revises: f26a04b5c6cf
Create Date: 2024-09-23 19:44:33.884642

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0191f5acdfa7'
down_revision: Union[str, None] = 'f26a04b5c6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=ON;")
    with op.batch_alter_table('buttons_infos', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_buttons_infos_post_id", 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_media_session_join', schema=None) as batch_op:
        batch_op.alter_column('post_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('media_session_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.drop_column('id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_foreign_key("fk_posts_streamer_id", 'streamers', ['streamer_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('previews', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_previews_post_id", 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('published_posts', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_published_posts_media_platform_session_id", 'media_platform_sessions',
                                    ['media_session_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key("fk_published_posts_post_id", 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('streamer_media_session_join', schema=None) as batch_op:
        batch_op.alter_column('streamer_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        batch_op.alter_column('media_session_id',
                              existing_type=sa.INTEGER(),
                              nullable=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key("fk_streamer_media_session_join_streamer_id", 'streamers', ['streamer_id'], ['id'],
                                    ondelete='CASCADE')
        batch_op.create_foreign_key("fk_streamer_media_session_join_media_platform_session_id",
                                    'media_platform_sessions', ['media_session_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("PRAGMA foreign_keys=ON;")
    with op.batch_alter_table('streamer_media_session_join', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint("fk_streamer_media_session_join_streamer_id", type_='foreignkey')
        batch_op.drop_constraint("fk_streamer_media_session_join_media_platform_session_id", type_='foreignkey')
        # batch_op.create_foreign_key(None, 'streamers', ['streamer_id'], ['id'])
        # batch_op.create_foreign_key(None, 'media_platform_sessions', ['media_session_id'], ['id'])
        batch_op.alter_column('media_session_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('streamer_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    with op.batch_alter_table('published_posts', schema=None) as batch_op:
        batch_op.drop_constraint("fk_published_posts_media_platform_session_id", type_='foreignkey')
        batch_op.drop_constraint("fk_published_posts_post_id", type_='foreignkey')
        # batch_op.create_foreign_key(None, 'media_platform_sessions', ['media_session_id'], ['id'])
        # batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('previews', schema=None) as batch_op:
        batch_op.drop_constraint("fk_previews_post_id", type_='foreignkey')
        # batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint("fk_posts_streamer_id", type_='foreignkey')

    with op.batch_alter_table('post_media_session_join', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('media_session_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.alter_column('post_id',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    with op.batch_alter_table('buttons_infos', schema=None) as batch_op:
        batch_op.drop_constraint("fk_buttons_infos_post_id", type_='foreignkey')
        # batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###
