"""initial migration

Revision ID: 24f698525a5c
Revises: 
Create Date: 2024-09-24 00:02:49.706655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f698525a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_platforms',
    sa.Column('name', sa.Enum('TELEGRAM', 'DISCORD', name='mediaplatformnames'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('stream_platforms',
    sa.Column('name', sa.Enum('Twitch', name='streamplatformnames'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('media_platform_sessions',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('media_name', sa.Enum('TELEGRAM', 'DISCORD', name='mediaplatformnames'), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('extra_field', sa.String(), nullable=True),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['media_name'], ['media_platforms.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stream_platform_sessions',
    sa.Column('stream_platform_name', sa.Enum('Twitch', name='streamplatformnames'), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('extra_field', sa.String(), nullable=True),
    sa.Column('expires_in', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['stream_platform_name'], ['stream_platforms.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streamers',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('stream_platform_name', sa.Enum('Twitch', name='streamplatformnames'), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['stream_platform_name'], ['stream_platforms.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('streamer_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streamer_media_session_join',
    sa.Column('streamer_id', sa.Integer(), nullable=False),
    sa.Column('media_session_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['media_session_id'], ['media_platform_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['streamer_id'], ['streamers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('streamer_id', 'media_session_id')
    )
    op.create_table('buttons_infos',
    sa.Column('buttons_info', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_media_session_join',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('media_session_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['media_session_id'], ['media_platform_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'media_session_id')
    )
    op.create_table('previews',
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('published_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('media_session_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['media_session_id'], ['media_platform_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('published_posts')
    op.drop_table('previews')
    op.drop_table('post_media_session_join')
    op.drop_table('buttons_infos')
    op.drop_table('streamer_media_session_join')
    op.drop_table('posts')
    op.drop_table('streamers')
    op.drop_table('stream_platform_sessions')
    op.drop_table('media_platform_sessions')
    op.drop_table('stream_platforms')
    op.drop_table('media_platforms')
    # ### end Alembic commands ###
