"""add initial data

Revision ID: a9bb2beaf798
Revises: 24f698525a5c
Create Date: 2024-09-24 00:02:57.169314

"""
import asyncio
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'a9bb2beaf798'
down_revision: Union[str, None] = '24f698525a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from src.db.migrations.init_data import (
    init_platforms,
    init_medias,
    delete_platforms,
    delete_medias,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asyncio.run(init_platforms())
    asyncio.run(init_medias())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asyncio.run(delete_platforms())
    asyncio.run(delete_medias())
    # ### end Alembic commands ###
