"""add initial data

Revision ID: d8af3072516c
Revises: 7e7a1b6c9619
Create Date: 2024-09-22 00:53:09.470274

"""

import asyncio
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d8af3072516c"
down_revision: Union[str, None] = "7e7a1b6c9619"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from src.db.migrations.init_data import (
    init_platforms,
    init_medias,
    delete_platforms,
    delete_medias,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asyncio.run(init_platforms())
    asyncio.run(init_medias())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asyncio.run(delete_platforms())
    asyncio.run(delete_medias())
    # ### end Alembic commands ###
